<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="WIN-39319556043" failures="1" tests="1" name="Login" time="10.153" errors="0" timestamp="2022-06-30T19:08:03 CST">
  <testcase classname="com.rs.test.login.Login" name="loginTest" time="2.856">
    <failure type="java.lang.AssertionError" message="The login was successful expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The login was successful expected [true] but found [false]
at com.rs.test.pageObjectModel.login.LoginVerificationPO.verifyLogin(LoginVerificationPO.java:131)
at com.rs.test.login.Login.loginTest(Login.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Login -->
